model:
  os: "strang"                     # splitting method, strang, lie-trotter
  order:  "ADR"                    # splitting order, ADR, DRA
  integrator: "RK4"                 # integrator, FE, RK4


trainer:
  num_epochs: 200            # Number of epochs to train the model
  learining_rate: 1e-4      # Initial learning rate
  
output_dir: /home/ndj376/ADRnet/AdvectionNet/PDEBench_SWE_ADRNet_Pred50/test_results


